name       : httrack
version    : 3.48.22
release    : 2
source     :
    - http://download.httrack.com/httrack-3.48.22.tar.gz : b2831ad7b48e933959f83a9de8a72bcaa0f8eb87e9453ad85debd50d33a9c48f
license    : GPL-3.0
component  : network.download
summary    : A command line tool for mirroring websites.
description: |
    A powerful command line tool for mirroring and making offline copies of websites.
setup      : |
    %configure  --disable-static
build      : |
    %make
install    : |
    %make_install
