name       : httrack
version    : 3.48.21
release    : 1
source     :
    - https://github.com/xroche/httrack/archive/3.48.21.tar.gz : 1560199f5c66e007bc634af0e03ccef67713a3777eaf19dec62acf77cbb39edf
license    : GPL-3.0
component  : network.download
summary    : A command line tool for mirroring websites.
description: |
    A powerful command line tool for mirroring and making offline copies of websites.
setup      : |
    %configure  --disable-static
build      : |
    %make
install    : |
    %make_install
