name       : httrack
version    : 3.49.2
release    : 4
source     :
    - http://mirror.httrack.com/httrack-3.49.2.tar.gz : 3477a0e5568e241c63c9899accbfcdb6aadef2812fcce0173688567b4c7d4025
license    : GPL-3.0
component  : network.download
summary    : A command line tool for mirroring websites.
description: |
    A powerful command line tool for mirroring and making offline copies of websites.
setup      : |
    %configure --disable-static \
               --disable-online-unit-tests
build      : |
    %make
install    : |
    %make_install
