name       : httrack
version    : 3.49.4
release    : 7
source     :
    - git|https://github.com/xroche/httrack.git : 4f24477a13e53346577691a0193e588e9ba992aa
license    : GPL-3.0-or-later
component  : network.download
summary    : A command line tool for mirroring websites.
description: |
    A powerful command line tool for mirroring and making offline copies of websites.
setup      : |
    %configure --disable-static --disable-online-unit-tests
build      : |
    %make
install    : |
    %make_install
