name       : httrack
version    : 3.49.1
release    : 3
source     :
    - http://mirror.httrack.com/httrack-3.49.1.tar.gz : 8640ab00cabc9189667cc88829620ce08ac796688f0ef94876350d14fbe7a842
license    : GPL-3.0
component  : network.download
summary    : A command line tool for mirroring websites.
description: |
    A powerful command line tool for mirroring and making offline copies of websites.
setup      : |
    %configure  --disable-static
build      : |
    %make
install    : |
    %make_install
